global using Xunit;
global using ToDoDevSecOpsMinimalAPI.Application.Common.Models;
global using ToDoDevSecOpsMinimalAPI.Application.Infrastructure.Persistence;
global using ToDoDevSecOpsMinimalAPI.Application.Infrastructure.Services;
global using ToDoDevSecOpsMinimalAPI.Application.Common.Interfaces;
global using ToDoDevSecOpsMinimalAPI.Application.Domain.ToDos;
global using Microsoft.EntityFrameworkCore;
global using ToDoDevSecOpsMinimalAPI.Application.Endpoints;
global using Microsoft.AspNetCore.Http.HttpResults;
