@ToDoDevSecOpsMinimalAPI_HostAddress = https://localhost:5001/api

POST {{ToDoDevSecOpsMinimalAPI_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{ToDoDevSecOpsMinimalAPI_HostAddress}}/todoitems

###

DELETE {{ToDoDevSecOpsMinimalAPI_HostAddress}}/todoitems/1

###

GET {{ToDoDevSecOpsMinimalAPI_HostAddress}}/todoitems/1

###

PUT {{ToDoDevSecOpsMinimalAPI_HostAddress}}/todoitems/2
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}
###
